[package]
name = "upaya-plugin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Plugin interface for Upaya Shell"

[dependencies]
upaya-core = { path = "../upaya-core" }
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
wasmtime.workspace = true 