[package]
name = "upaya-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core functionality for Upaya Shell"

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
wasmtime.workspace = true
git2.workspace = true
reqwest.workspace = true
tracing.workspace = true 